'use strict';
(async () => {
const assert = require('assert');
const contract = await import('../public/js/dashboard-family-contract.mjs');
const { resolveDashboardFamily, resolveFamilyComponentType, expandFamilyBlockTypes } = await import('../public/js/dashboard-family-runtime.mjs');
const runtimeSource = require('fs').readFileSync('public/js/dashboard-family-runtime.mjs', 'utf8');
const updaterSource = require('fs').readFileSync('public/js/updater.js', 'utf8');
const editorSource = require('fs').readFileSync('public/js/editor.js', 'utf8');
const roundtrip = await import('../public/js/dashboard-config-roundtrip.mjs');
assert.deepStrictEqual([...expandFamilyBlockTypes(['stat-metric'])], ['stat-metric', 'text-metric']);
assert.strictEqual(resolveFamilyComponentType('stat-metric'), 'text-metric');
assert.strictEqual(resolveFamilyComponentType('existing-type'), 'existing-type');
assert(updaterSource.includes("import { expandFamilyBlockTypes } from './dashboard-family-runtime.mjs'") && updaterSource.includes('const blockTypes = expandFamilyBlockTypes('), 'updater must import and call family expansion');
assert(editorSource.includes('resolveFamilyComponentType') && (editorSource.match(/componentBuilders\[resolveFamilyComponentType\(/g) || []).length >= 2, 'editor must resolve builders for refresh/build');
assert(editorSource.includes('mergePersistedBlock'));
const families = ['stat-metric','segmented-gauge','multi-series-timeseries','multi-series-bar-gauge','static-text','string-state'];
for (const name of families) {
  const entry = contract.getFamily(name);
  const resolved = resolveDashboardFamily(name);
  assert.strictEqual(typeof resolved.builder, 'function', `${name} must resolve a callable builder`);
  assert.strictEqual(typeof resolved.update, 'function', `${name} must resolve callable updater behavior`);
  assert.strictEqual(typeof resolved.persist, 'function', `${name} must resolve editor persistence capability`);
  assert.strictEqual(typeof resolved.settings, 'function', `${name} must resolve settings capability`);
  const existing = { config: { thresholds: [{ value: 4 }, { value: 4 }] }, vendorExtension: { keep: true } };
  const persisted = resolved.persist(existing, { gridX: 1 });
  assert.deepStrictEqual(persisted, roundtrip.mergePersistedBlock(existing, { gridX: 1 }));
  assert.strictEqual(resolved.settings({ config: { thresholds: [{ value: 4 }, { value: 4 }] } }).thresholds.length, 2);
  assert.deepStrictEqual(resolved.settings({ config: { version: 1 } }), { version: 1 });
  assert.strictEqual(resolved.update({ metric: 'missing' }, {}), null, `${name} updater must resolve missing data to no-data`);
  assert.strictEqual(typeof resolved.builder, 'function');
  assert(entry, `missing family ${name}`);
  assert.strictEqual(entry.version, 1);
  for (const key of ['renderer','updater','editor','settings']) assert(entry.registration[key], `${name} missing ${key} registration`);
  assert.strictEqual(entry.registration.updater, 'expandFamilyBlockTypes');
  assert.strictEqual(entry.registration.editor, 'resolveFamilyComponentType');
  assert.strictEqual(resolveFamilyComponentType(name), entry.componentType);
  assert(contract.validateConfig(name, contract.defaultConfig(name)).valid, `${name} default invalid`);
  assert(!contract.validateConfig(name, { version: 99 }).valid, `${name} accepts unsupported version`);
  assert(!contract.validateConfig(name, { version: 1, bindings: [] }).valid, `${name} accepts malformed bindings`);
}
console.log('dashboard-family-registry: PASS');
})().catch(e => { console.error(e); process.exitCode = 1; });
