import assert from 'node:assert/strict';
import fs from 'node:fs';
import { listDashboardPresets, createPresetBlock, previewTemplateImport, applyTemplateImport } from '../public/js/dashboard-presets.mjs';
import { componentBuilders } from '../public/js/components/index.js';
const canonical = JSON.parse(fs.readFileSync('templates/dashboard-43-panel-template.json', 'utf8'));
const presets = listDashboardPresets(canonical);
assert.equal(presets.length, 43);
assert.equal(new Set(presets.map(p => p.panelId)).size, 43);
assert.ok(presets.every(p => p.title && componentBuilders[p.type]));
assert.deepEqual(presets.map(p => p.panelId), canonical.dashboards.flatMap(d => d.layout.map(p => p.panelId)));
const preset = presets[0];
let id = 0;
const first = createPresetBlock(preset, () => `runtime-${++id}`);
const second = createPresetBlock(preset, () => `runtime-${++id}`);
assert.notEqual(first.id, second.id);
first.config.binding.metric = 'mutated';
assert.notEqual(preset.config.binding.metric, 'mutated');
assert.equal(first.panelId, preset.panelId);
const preview = previewTemplateImport(canonical);
assert.equal(preview.dashboardCount, canonical.dashboards.length);
assert.equal(preview.cardCount, 43);
assert.deepEqual(preview.familyBreakdown, Object.fromEntries([...new Set(presets.map(p => p.type))].map(type => [type, presets.filter(p => p.type === type).length])));
const current = { dashboards: [{ id: 'same', name: 'Existing', layout: [{ id: 'panel-2', type: 'x' }] }], activeDashboard: 'same' };
const canceled = applyTemplateImport(current, canonical, 'cancel', () => 'unused');
assert.equal(canceled, null);
assert.equal(current.dashboards.length, 1);
const appended = applyTemplateImport(current, canonical, 'append');
assert.equal(appended.dashboards.length, current.dashboards.length + canonical.dashboards.length);
assert.equal(appended.dashboards[0].layout[0].id, 'panel-2');
const ids = appended.dashboards.flatMap(d => [d.id, ...d.layout.map(c => c.id)]);
assert.equal(new Set(ids).size, ids.length);
assert.deepEqual(applyTemplateImport(current, canonical, 'replace').dashboards, canonical.dashboards);
// The browser preset source is generated from, and must remain identical to, the canonical JSON.
const source = fs.readFileSync('public/js/dashboard-43-presets.mjs', 'utf8');
const embedded = JSON.parse(source.match(/export default (.*);/s)[1]);
assert.deepEqual(embedded, canonical);
const html = fs.readFileSync('public/editor.html', 'utf8');
assert.match(html, /\.blocks-panel[\s\S]*?overflow-y:\s*auto/);
assert.match(html, /@media \(max-width: 1200px\)[\s\S]*?\.blocks-panel[^{]*\{[^}]*max-height:\s*none/);
console.log('dashboard-presets-import: PASS');
