'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
(async () => {
  const source = fs.readFileSync(path.join(__dirname, '../public/js/components/metricTrendLogic.js'), 'utf8').replace("import { formatMetric } from './format.js';", `const formatMetric = (value, unit, opts) => ({ value: Number(value).toFixed(opts.decimals), unit, empty: false });`);
  const m = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
  const c = m.normalizeMetricTrendConfig({ preset: 'filled-body', value: { metric: 'load_kw', unit: 'kW' }, graph: { enabled: true, source: 'metric-history', metric: 'solar_kw', window: '24h' }, display: { precision: 4 }, mystery: 9 });
  assert.equal(c.preset, 'filled-body'); assert.equal(c.value.metric, 'load_kw'); assert.equal(c.graph.metric, 'solar_kw'); assert.equal(c.display.precision, 4); assert.equal(c.mystery, 9);
  const safe = m.normalizeMetricTrendConfig({ style: { bodyFill: 'red; background:url(x)', graphLineColor: '#123456' }, display: { valueFontSize: 500 }, graph: { min: -2, max: 2, scale: 'manual' } });
  assert.equal(safe.style.bodyFill, ''); assert.equal(safe.style.graphLineColor, '#123456'); assert.equal(safe.display.valueFontSize, 96); assert.equal(safe.graph.validScale, true);
  assert.equal(m.normalizeMetricTrendConfig({ graph: { scale: 'manual', min: 5, max: 2 } }).graph.validScale, false);
  assert.equal(m.trendValueFromState({ metrics: { p: { value: 0, unit: 'W' } } }, m.normalizeMetricTrendConfig({ value: { metric: 'p' } })), 0);
  assert.equal(m.trendValueFromState({ metrics: { p: { value: 0, quality: 'stale' } } }, m.normalizeMetricTrendConfig({ value: { metric: 'p' } })), null);
  assert.equal(m.trendValueFromState({ metrics: { p: { value: -0 } } }, m.normalizeMetricTrendConfig({ value: { metric: 'p' } })), -0);
  assert.equal(m.historyUrl('a b', '7d'), '/api/metrics/history?metric=a%20b&hours=168');
  assert.equal(m.historyTrendPath([{timestamp:0,value:2},{timestamp:1,value:2},{timestamp:2,value:2}]) !== '', true);
  assert.equal(m.historyTrendAreaPath('M0.00,-2.00 L40.00,12.00 M70.00,20.00 L100.00,25.00').split('Z').length - 1, 2);
  assert.equal(m.serverForecastDate({ daily: [{ date: '2026-10-04', actual_so_far: 0 }] }), '2026-10-04');
  assert.equal(m.forecastValue({ daily: [{ date: '2026-10-04', total_kwh: null }] }, 'today-total', '2026-10-04'), null);
  assert.equal(m.forecastValue({ daily:[{date:'2026-10-04',total_kwh:1}], hourly:[{period_end:'2026-10-04T23:00:00Z',energy_kwh:2}] }, 'today-remaining', '2026-10-04', Date.parse('2026-10-04T22:00:00Z')), null);
  assert.equal(m.finiteMetric(0), 0); assert.equal(m.finiteMetric('-2.5'), -2.5); assert.equal(m.finiteMetric(null), null); assert.equal(m.finiteMetric(Infinity), null);
  assert.equal(m.formatTrendValue(0, 'W', 1).value, '0.0'); assert.equal(m.formatTrendValue(-2.56, 'kW', 1).value, '-2.6');
  assert.equal(m.formatTrendValue(null, 'kWh', 1).value, '—');
  assert.equal(m.historyTrendPath([{timestamp:0,value:-2},{timestamp:1,value:0},{timestamp:2,value:null},{timestamp:3,value:4},{timestamp:4,value:6}]).split('M').length - 1, 2);
  const manualPath = m.historyTrendPath([{timestamp:0,value:-5},{timestamp:1,value:5},{timestamp:2,value:15}], 100, 50, {min:0,max:10});
  const plottedY = [...manualPath.matchAll(/[ML]([-0-9.]+),([-0-9.]+)/g)].map(x => Number(x[2]));
  assert.deepEqual(plottedY, [50,25,0]);
  const manualRuns = m.historyTrendPath([{timestamp:0,value:-5},{timestamp:1,value:5},{timestamp:2,value:null},{timestamp:3,value:15},{timestamp:4,value:5}],100,50,{min:0,max:10});
  assert.equal(manualRuns.split('M').length - 1, 2);
  assert.equal(m.historyTrendAreaPath(manualRuns,50).split('Z').length - 1,2);
  assert.deepEqual(m.metricHistoryRange([{value:-5},{value:5},{value:15}]), {min:-5,max:15}); // raw source range remains un-clamped
  const regularGap = m.historyTrendPath([0,1,3,4].map(timestamp=>({timestamp,value:timestamp})));
  assert.equal(regularGap.split('M').length - 1, 1);
  const outageGap = m.historyTrendPath([0,1,2,20,21].map(timestamp=>({timestamp,value:timestamp})));
  assert.equal(outageGap.split('M').length - 1, 2);
  assert.deepEqual(m.metricHistoryRange([{value:-4},{value:-2}]), {min:-4,max:-2});
  assert.equal(m.forecastValue({ daily:[{date:'2026-10-04',total_kwh:3},{date:'2026-10-05',total_kwh:5}], hourly:[{period_end:'2026-10-04T23:00:00Z',energy_kwh:2},{period_end:'2026-10-05T01:00:00Z',energy_kwh:1}] }, 'today-total', '2026-10-04'), 3);
  const hourly = [{ date:'2026-10-04', period_end:'2026-10-04T20:00:00Z', energy_kwh:2 }, { date:'2026-10-04', period_end:'2026-10-04T23:00:00Z', energy_kwh:1 }, { date:'2026-10-05', period_end:'2026-10-05T01:00:00Z', energy_kwh:9 }];
  const serverDay = { server_today:'2026-10-04', daily:[{date:'2026-10-04',total_kwh:3}], hourly };
  assert.equal(m.serverForecastDate(serverDay), '2026-10-04');
  assert.equal(m.forecastValue(serverDay, 'today-remaining', '2026-10-04', Date.parse('2026-10-04T22:00:00Z')), 1);
  assert.equal(m.forecastValue({daily:serverDay.daily,hourly:hourly.map(({date,...h})=>h)}, 'today-remaining', '2026-10-04', Date.parse('2026-10-04T19:00:00Z')), null);
  assert.deepEqual(m.forecastGraphPoints(serverDay,'today','2026-10-04').map(p=>p.value), [2,1]);
  assert.deepEqual(m.forecastGraphPoints({daily:serverDay.daily,hourly:hourly.map(({date,...h})=>h)},'today','2026-10-04'), []);
  assert.equal(m.forecastValue({...serverDay,hourly:[{date:'2026-10-04',period_end:'2026-10-04T19:00:00Z',energy_kwh:2}]}, 'today-remaining', '2026-10-04', Date.parse('2026-10-04T19:00:00Z')), 0);
  assert.equal(m.forecastValue({...serverDay,hourly:[{date:'2026-10-04',period_end:'invalid',energy_kwh:2}]}, 'today-remaining', '2026-10-04', Date.parse('2026-10-04T18:00:00Z')), null);
  assert.equal(m.serverForecastDate({server_today:'2026-02-30',daily:[{date:'2026-10-04',actual_so_far:0}]}), '2026-10-04');
  assert.equal(m.forecastValue({ daily:[], hourly:[] }, 'tomorrow-total', '2026-10-04'), null);
  console.log('metric trend logic tests passed');
})().catch(e => { console.error(e); process.exit(1); });
