import test from 'node:test';
import assert from 'node:assert/strict';
import { ensureChartJS } from '../public/js/chartLoader.js';
import { readFileSync } from 'node:fs';
import { initPowerChart, refreshPowerChartFor, updatePowerChartData } from '../public/js/charts.js';
import { normalizePowerStatsConfig, formatPowerStat, buildPowerStatsSection, updatePowerStatsSection, createPowerStatsRequestGate, resolvePowerStatsField } from '../public/js/components/powerChartStats.js';

test('power stats sizing keeps headers and numeric readings intact inside a local scroller',()=>{
  const css=readFileSync(new URL('../public/style.css',import.meta.url),'utf8');
  const rule=selector=>{const start=css.indexOf(`${selector} {`);assert.notEqual(start,-1,`missing scoped CSS rule: ${selector}`);return css.slice(start+selector.length+2,css.indexOf('}',start));};
  const table=rule('.power-stats-table'),cells=rule('.power-stats-table thead th, .power-stats-table tbody th, .power-stats-table td'),labels=rule('.power-stats-table tbody th');
  assert.ok(css.includes('.power-stats { overflow-x: auto'));assert.ok(css.includes('max-width: 100%; min-width: 0; margin: .35rem'));assert.ok(table.includes('width: max-content'));assert.ok(table.includes('min-width: 100%'));
  assert.match(cells,/white-space:\s*nowrap/);assert.match(cells,/overflow-wrap:\s*normal/);assert.match(cells,/word-break:\s*normal/);
  assert.match(labels,/white-space:\s*normal/);assert.match(labels,/overflow-wrap:\s*break-word/);
});

class FakeNode {
  constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.style={setProperty(k,v){this[k]=v;}};this.dataset={};this.hidden=false;this.listeners={};this._text='';}
  set textContent(v){this._text=String(v??'');this.children=[];} get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
  set className(v){this._class=v;} get className(){return this._class||'';}
  setAttribute(k,v){this.attributes[k]=String(v);} getAttribute(k){return this.attributes[k]??null;} append(...ns){ns.forEach(n=>n.parentNode=this);this.children.push(...ns);} prepend(n){n.parentNode=this;this.children.unshift(n);} replaceChildren(...ns){this.children=ns;ns.forEach(n=>n.parentNode=this);}
  remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);}
  addEventListener(k,fn){this.listeners[k]=fn;} querySelector(sel){return this.querySelectorAll(sel)[0]||null;}
  querySelectorAll(sel){const match=n=>sel==='tbody'?n.tagName==='TBODY':sel==='thead'?n.tagName==='THEAD':sel==='.power-stats-warning'?n.className==='power-stats-warning':sel==='.power-stats-unavailable'?n.className==='power-stats-unavailable':sel==='table'?n.tagName==='TABLE':sel==='tr'?n.tagName==='TR':sel==='td'?n.tagName==='TD':false;return this.children.flatMap(n=>[...(match(n)?[n]:[]),...n.querySelectorAll(sel)]);}
  get tag(){return this.tagName;} get innerHTML(){return this.textContent;}
}
global.document={createElement:t=>new FakeNode(t)};
test('power stats table is a sibling after a canvas-only wrapper',()=>{const source=readFileSync(new URL('../public/js/components/chartPower.js',import.meta.url),'utf8');assert.match(source,/wrapper\.appendChild\(canvas\);\s*if \(config\.stats && config\.stats\.enabled === true\) container\.insertBefore\(buildPowerStatsSection\(config\), wrapper\.nextSibling\);/);assert.doesNotMatch(source,/wrapper\.appendChild\(buildPowerStatsSection/);});

test('power chart initializes with appearance axes and empty bounds without ReferenceError',async()=>{
  let constructed;const container={dataset:{chartConfig:JSON.stringify({appearance:{axisUnit:'kW',height:350,axisMin:'',axisMax:'',axes:{left:{unit:'W',min:'',max:'',scale:'linear'},right:{unit:'kW',min:0,max:''}}}})},querySelector:()=>null};
  const canvasWrap={style:{},closest:()=>canvasWrap};const canvas={dataset:{},style:{},isConnected:true,closest:selector=>selector==='.power-chart-canvas-wrap'?canvasWrap:container,getContext:()=>({})};container.dataset.chartDatasets='[]';
  global.document.head={appendChild(script){queueMicrotask(()=>script.onload());}};global.document.querySelectorAll=()=>[canvas];global.getComputedStyle=()=>({getPropertyValue:()=>''});global.document.documentElement={getAttribute:()=>null};
  global.Chart=class {constructor(_ctx,config){constructed=config;this.destroy=()=>{};}};
  await ensureChartJS();const made=initPowerChart();assert.equal(made.length,1);assert.equal(canvasWrap.style.height,'350px');assert.equal(canvas.style.height,undefined);assert.equal(constructed.options.scales.y.min,undefined);assert.equal(constructed.options.scales.y.max,undefined);assert.equal(constructed.options.scales.yRight.min,0);
});
const response={schemaVersion:1,range:{from:10,to:20},fields:{pv_power:{status:'ok',unit:'W',mean:0,max:20,min:-2,last:{timestamp:19,value:20},fidelity:{warnings:[]}}}};
test('stats config preserves unknown keys and clamps settings while blank bounds remain automatic',()=>{const cfg=normalizePowerStatsConfig({custom:7,stats:{enabled:true,customNested:'keep',columns:[{key:'mean',precision:99},{key:'mean',label:'duplicate'}],tableStyle:{fontSizePx:999,textColor:'javascript:bad'}}});assert.equal(cfg.enabled,true);assert.equal(cfg.customNested,'keep');assert.equal(cfg.columns.length,1);assert.equal(cfg.columns[0].precision,6);assert.equal(cfg.tableStyle.fontSizePx,24);assert.equal(cfg.tableStyle.textColor,'theme');});
test('formatter preserves zero, unavailable and scaled signed values',()=>{assert.equal(formatPowerStat(0,{unit:'W'},{unit:'W'}),'0');assert.equal(formatPowerStat(null,{unit:'W'},{unit:'W'}),'—');assert.equal(formatPowerStat(-1250,{unit:'W'},{unit:'kW',precision:2}),'-1.25');});
test('power aliases map to canonical stats fields without treating export as import',()=>{assert.equal(resolvePowerStatsField('PVPower'),'pv_power');assert.equal(resolvePowerStatsField('grid_import'),'grid_power');assert.equal(resolvePowerStatsField('grid_export'),'grid_export_power');assert.equal(resolvePowerStatsField('battery_charging'),'battery_charge_power');});
test('newer range/config refresh invalidates older snapshots',()=>{const gate=createPowerStatsRequestGate(),old=gate.capture({from:10,to:20,configRevision:1}),current=gate.capture({from:20,to:30,configRevision:2});assert.equal(Object.isFrozen(current),true);assert.equal(gate.isCurrent(old),false);assert.equal(gate.isCurrent(current),true);});
test('table renders controls, accessible warnings, units, and supports keyboard visibility toggles',()=>{const root=buildPowerStatsSection({stats:{enabled:true,title:'Power',headerVisible:false,density:'compact',tableStyle:{fontSizePx:18,rowSpacingPx:4,valueAlign:'center'}}});let toggles=0;assert.equal(root.querySelector('thead').hidden,true);assert.equal(root.style.fontSize,'18px');assert.equal(root.dataset.density,'compact');assert.equal(updatePowerStatsSection(root,{...response,fields:{...response.fields,pv_power:{...response.fields.pv_power,fidelity:{warnings:[{code:'estimated',message:'Estimated samples'}]}}}},[{metric:'PVPower',label:'PV',unit:'kW',color:'#f59e0b'}],{from:10,to:20},{toggleSeries:()=>toggles++,isHidden:()=>false}),true);const row=root.querySelector('tbody').children[0];assert.match(root.textContent,/PV \(kW\)/);assert.match(root.textContent,/Estimated samples/);assert.equal(root.querySelector('.power-stats-warning').attributes['aria-live'],'polite');row.listeners.keydown({key:'Enter',preventDefault(){}});assert.equal(toggles,1);});
test('precision, layout tokens, shared swatch and compact accessible stale timestamp follow config',()=>{const root=buildPowerStatsSection({stats:{enabled:true,columns:[{key:'mean',precision:0},{key:'last',showTimestamp:false,staleAfterSeconds:1}],tableStyle:{headerAlign:'center',labelAlign:'end',valueAlign:'center',rowSpacingPx:6}}});assert.equal(root.style['--power-stats-header-align'],'center');assert.equal(root.style['--power-stats-label-align'],'end');assert.equal(root.style['--power-stats-value-align'],'center');assert.equal(normalizePowerStatsConfig({stats:{columns:[{key:'mean',precision:null}]}}).columns[0].precision,null);const old=Math.floor(Date.now()/1000)-20;updatePowerStatsSection(root,{...response,fields:{pv_power:{...response.fields.pv_power,unit:'kW',mean:1.234,last:{timestamp:old,value:4}}}},[{metric:'PVPower',unit:'kW',color:'red'}],{from:10,to:20},{resolveColor:()=> 'rgb(1, 2, 3)'});const row=root.querySelector('tbody').children[0],cells=row.children;assert.match(cells[1].textContent,/1 kW/);assert.match(cells[2].textContent,/stale, 20s old/);assert.match(cells[2].attributes['aria-label'],/last sample/);assert.equal(cells[2].children[0].title,new Date(old*1000).toISOString());assert.equal(row.children[0].children[0].style.color,'rgb(1, 2, 3)');});
test('schema or range mismatch clears stale rows and reports unavailable stats',()=>{const root=buildPowerStatsSection({stats:{enabled:true}});updatePowerStatsSection(root,response,[{metric:'PVPower'}],{from:10,to:20});assert.equal(updatePowerStatsSection(root,{...response,schemaVersion:7},[],{from:10,to:20}),false);assert.equal(root.hidden,false);assert.equal(root.querySelector('tbody').children.length,0);assert.match(root.querySelector('.power-stats-unavailable').textContent,/schema or range/);});
test('repeated refresh replaces statistics rows, visibility filters peers, and range changes do not accumulate rows',()=>{const root=buildPowerStatsSection({stats:{enabled:true}}),items=[{metric:'PVPower',label:'PV'},{metric:'grid_import',label:'Grid'}];const payload={...response,fields:{...response.fields,grid_power:{status:'ok',unit:'W',mean:3,max:4,min:2,last:{timestamp:19,value:3},fidelity:{warnings:[]}}}};const count=()=>root.querySelector('tbody').children.length;updatePowerStatsSection(root,payload,items,{from:10,to:20});assert.equal(count(),2);updatePowerStatsSection(root,payload,items,{from:10,to:20});assert.equal(count(),2);updatePowerStatsSection(root,payload,items,{from:10,to:20},{isHidden:index=>index===1});assert.equal(count(),1);updatePowerStatsSection(root,payload,items,{from:10,to:20});assert.equal(count(),2);for(let range=21;range<=23;range++){updatePowerStatsSection(root,{...payload,range:{from:range,to:range+10}},items,{from:range,to:range+10});assert.equal(count(),2);}});
test('warnings remain visible when tooltips are disabled and are scoped to rendered rows',()=>{const root=buildPowerStatsSection({stats:{enabled:true,tableStyle:{tooltip:false}}});const warning={...response,fields:{pv_power:{...response.fields.pv_power,fidelity:{warnings:[{code:'estimated',message:'PV estimated'}]}},grid_power:{status:'ok',unit:'W',mean:3,max:4,min:2,last:{timestamp:19,value:3},fidelity:{warnings:[{code:'grid_only',message:'Grid only'}]}}}};updatePowerStatsSection(root,warning,[{metric:'PVPower'},{metric:'grid_import'}],{from:10,to:20},{isHidden:index=>index===1});assert.match(root.querySelector('.power-stats-warning').textContent,/PV estimated/);assert.doesNotMatch(root.querySelector('.power-stats-warning').textContent,/Grid only/);assert.match(root.querySelector('tbody').children[0].children[1].getAttribute('aria-label'),/PV estimated/);});
test('numeric overflow warning is rendered as a human explanation',()=>{const root=buildPowerStatsSection({stats:{enabled:true}});updatePowerStatsSection(root,{...response,fields:{pv_power:{...response.fields.pv_power,fidelity:{warnings:[{code:'numeric_overflow'}]}}}},[{metric:'PVPower'}],{from:10,to:20});assert.match(root.querySelector('.power-stats-warning').textContent,/exceeded the numeric range/);});
test('series values use assigned axis units independently of series display unit',()=>{const container={dataset:{range:'24h',chartConfig:JSON.stringify({fill:false,appearance:{axes:{left:{unit:'kW'},right:{unit:'W'}}}}),chartDatasets:JSON.stringify([{metric:'solar',label:'Solar',unit:'W',axis:'left'},{metric:'load',label:'Load',unit:'kW',axis:'right'}])}};const chart={data:{datasets:[]},options:{scales:{x:{time:{}},y:{title:{}},yRight:{title:{}}},plugins:{legend:{},tooltip:{}}},update(){}};updatePowerChartData(chart,container,[{timestamp:1,solar_kw:2,consumption_kw:3}]);assert.equal(chart.data.datasets[0].data[0].y,2);assert.equal(chart.data.datasets[0].unit,'W');assert.equal(chart.data.datasets[1].data[0].y,3000);assert.equal(chart.options.scales.y.title.text,'Power (kW)');assert.equal(chart.options.scales.yRight.title.text,'Power (W)');});
test('3-day power refresh requests and renders stats over the same 72-hour window',async()=>{const mount=buildPowerStatsSection({stats:{enabled:true}});let url;const previousFetch=global.fetch;global.fetch=async value=>{url=value;const q=new URL(value,'http://local').searchParams;return{ok:true,json:async()=>({...response,range:{from:Number(q.get('from')),to:Number(q.get('to'))}})};};const container={dataset:{range:'3d',chartConfig:JSON.stringify({stats:{enabled:true},fill:false}),chartDatasets:JSON.stringify([{metric:'solar',label:'Solar'}])},querySelector:()=>mount};const chart={data:{datasets:[]},options:{scales:{x:{time:{}},y:{title:{}},yRight:{title:{}}},plugins:{legend:{},tooltip:{}}},update(){},isDatasetVisible:()=>true,getDatasetMeta:()=>({hidden:false}),hide(){},show(){}};try{await refreshPowerChartFor({chart,container},{powerHistory:[{timestamp:Date.now(),solar_kw:1}]});const q=new URL(url,'http://local').searchParams;assert.equal(Number(q.get('to'))-Number(q.get('from')),72*3600);assert.equal(mount.hidden,false);assert.equal(mount.querySelector('tbody').children.length,1);}finally{global.fetch=previousFetch;}});
test('delayed stats response cannot commit after the range changes',async()=>{const mount=buildPowerStatsSection({stats:{enabled:true}});let release,requested;const deferred=new Promise(resolve=>{release=resolve;}),arrived=new Promise(resolve=>{requested=resolve;});const oldFetch=global.fetch;global.fetch=async()=>{requested();return deferred;};const container={dataset:{range:'24h',chartConfig:JSON.stringify({stats:{enabled:true},fill:false}),chartDatasets:JSON.stringify([{metric:'solar',label:'Solar'}])},querySelector:()=>mount};const chart={data:{datasets:[]},options:{scales:{x:{time:{}},y:{title:{}},yRight:{title:{}}},plugins:{legend:{},tooltip:{}}},update(){},isDatasetVisible:()=>true,getDatasetMeta:()=>({hidden:false}),hide(){},show(){}};try{const pending=refreshPowerChartFor({chart,container},{powerHistory:[{timestamp:Date.now(),solar_kw:1}]});await arrived;container.dataset.range='3d';release({ok:true,json:async()=>response});await pending;assert.equal(mount.querySelector('tbody').children.length,0);}finally{global.fetch=oldFetch;}});
test('delayed stats response cannot commit after the dataset snapshot changes',async()=>{const mount=buildPowerStatsSection({stats:{enabled:true}});let release,requested;const request=new Promise(resolve=>{release=resolve;}),wait=new Promise(resolve=>{requested=resolve;});const previousFetch=global.fetch;global.fetch=async url=>{requested();const q=new URL(url,'http://local').searchParams;return request.then(r=>({...r,json:async()=>({...response,range:{from:Number(q.get('from')),to:Number(q.get('to'))}})}));};const container={dataset:{range:'24h',chartConfig:JSON.stringify({stats:{enabled:true},fill:false}),chartDatasets:JSON.stringify([{metric:'solar',label:'Solar',color:'#f59e0b'}])},querySelector:()=>mount};const chart={data:{datasets:[]},options:{scales:{x:{time:{}},y:{title:{},},yRight:{title:{}}},plugins:{legend:{},tooltip:{}}},update(){},isDatasetVisible:()=>true,getDatasetMeta:()=>({hidden:false}),hide(){},show(){}};try{const pending=refreshPowerChartFor({chart,container},{powerHistory:[{timestamp:Date.now(),solar_kw:1}]});await wait;container.dataset.chartDatasets=JSON.stringify([{metric:'load',label:'Load',color:'#000000'}]);release({ok:true,json:async()=>response});await pending;assert.equal(mount.querySelector('tbody').children.length,0);}finally{global.fetch=previousFetch;}});
