import assert from 'node:assert/strict';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
const logic = await import(new URL('../public/js/segmented-gauge-logic.mjs', import.meta.url));
const config = {min:0,max:100,segments:30,spacing:0.3,thresholds:[{value:0,color:'red'},{value:15,color:'orange'},{value:30,color:'yellow'},{value:50,color:'green'}],markers:true,labels:false,endpoint:'point',sparkline:'area',reducer:'lastNotNull'};
assert.deepEqual(logic.normalizeSegmentedGauge(config), config);
assert.deepEqual(logic.segmentedGaugeSegmentColors(0, 100, 10, config.thresholds), ['red','orange','yellow','yellow','green','green','green','green','green','green']);
assert.deepEqual(logic.segmentedGaugeSegmentColors(0, 100, 4, config.thresholds), ['orange','green','green','green']);
const colors30 = logic.segmentedGaugeSegmentColors(0,100,30,config.thresholds);
assert.equal(colors30[0], 'red');
assert.deepEqual([...new Set(colors30)], ['red','orange','yellow','green']);
assert.deepEqual(colors30.map((color,i)=>color !== colors30[i-1] ? color : null).filter(Boolean), ['red','orange','yellow','green']);
const gaugeSource = fs.readFileSync(new URL('../public/js/components/segmentedGauge.js', import.meta.url),'utf8');
assert.ok(gaugeSource.indexOf('const hasFallback=cfg.fallback?.enabled===true') < gaugeSource.indexOf("root.dataset.status=ok?"));
assert.match(gaugeSource,/cfg\.fallback\?\.enabled===true/);
assert.match(gaugeSource,/root\.dataset\.status=ok\?'data':hasFallback\?'fallback':'no-data'/);
assert.match(gaugeSource,/root\.dataset\.measured=String\(ok\)/);
assert.match(gaugeSource,/if\(ok\) meter\.setAttribute\('aria-valuenow'/);
assert.match(gaugeSource,/else meter\.removeAttribute\('aria-valuenow'\)/);
const css = fs.readFileSync(new URL('../public/style.css',import.meta.url),'utf8');
for (const cls of ['.stat-metric-card','.segmented-gauge-card','.stat-sparkline','.segmented-gauge-sparkline','.stat-sparkline-none','.segmented-gauge-sparkline-none','.stat-fallback-label','.segmented-gauge-fallback','.segmented-gauge-track','.segmented-gauge-segment','.segmented-gauge-marker','.segmented-gauge-endpoint','.segmented-gauge-value']) assert.ok(css.includes(cls),`missing ${cls}`);
const phase2Css = css.match(/\/\* Phase 2 metric-card presentation \*\/[\s\S]*?(?=\/\* Bar Gauge Card \*\/)/)?.[0];
assert.ok(phase2Css,'Phase-2 CSS block exists');
assert.match(phase2Css,/gap:\s*3px/);
assert.doesNotMatch(phase2Css,/gradient|glow|box-shadow/i);
console.log('segmented-gauge-parity.test.js: passed');
